import { PlatformRules } from '@/types';

export const PLATFORM_RULES: Record<string, PlatformRules> = {
  amazon: {
    name: 'Amazon',
    titleRange: { min: 80, max: 200 },
    minDescription: 1000,
    maxTags: 249,
    tagFormat: 'space-separated-bytes',
    guidelines: [
      'Title Case for all words',
      'No symbols: ™ ! * © ®',
      'No promotional phrases: Best Seller, Free Shipping, #1',
      'Front-load primary keyword in first 80 characters',
      'Exactly 5 bullet points, max 250 chars each',
      'Backend keywords: max 249 bytes, no title word repetition',
    ],
  },
  ebay: {
    name: 'eBay',
    titleRange: { min: 60, max: 80 },
    minDescription: 400,
    maxTags: 10,
    tagFormat: 'item-specifics',
    guidelines: [
      'Exactly 80 characters — maximize every character',
      'No fluff: L@@K, Wow, Fast Shipping, Must See',
      'Priority: Brand + Model/MPN + Product + Key Spec + Condition',
      'Clean mobile-optimized HTML, no scripts or iframes',
      'Item specifics: Brand, MPN, GTIN, Material',
    ],
  },
  walmart: {
    name: 'Walmart',
    titleRange: { min: 40, max: 75 },
    minDescription: 400,
    minDescriptionWords: 150,
    maxTags: 10,
    tagFormat: 'product-attributes',
    guidelines: [
      'Title strictly 50-75 characters',
      'Brand name must be first word',
      'Title Case only',
      'No retailer-specific info',
      '3-10 key features, max 80 chars each',
      'Description: minimum 150 words in paragraph format',
    ],
  },
  etsy: {
    name: 'Etsy',
    titleRange: { min: 100, max: 140 },
    minDescription: 500,
    maxTags: 13,
    tagFormat: 'multi-word-phrases',
    guidelines: [
      'Primary keyword in first 40 characters',
      'Natural gifting language',
      'Exactly 13 multi-word tags, no single-word tags',
      'Max 20 characters per tag',
      'Warm conversational description tone',
      'Mention gifting occasions and recipients',
    ],
  },
  shopify: {
    name: 'Shopify',
    titleRange: { min: 55, max: 70 },
    minDescription: 300,
    maxTags: 10,
    tagFormat: 'comma-separated',
    guidelines: [
      'H1 title under 70 characters',
      'SEO Meta Title under 60 characters',
      'First 160 chars of description = meta description',
      'Use H2/H3 subheadings for structure',
      'Focus on benefits and long-tail keywords',
    ],
  },
  woocommerce: {
    name: 'WooCommerce',
    titleRange: { min: 55, max: 70 },
    minDescription: 300,
    maxTags: 12,
    tagFormat: 'comma-separated',
    guidelines: [
      'H1 title under 70 characters',
      'SEO Meta Title under 60 characters',
      'First 160 chars of description = meta description',
      'Schema-friendly structured content',
      'Use H2/H3 subheadings for structure',
    ],
  },
};
