import { useState } from 'react';
import { Download, FileText, Mail, Copy, Save, ChevronDown } from 'lucide-react';
import Button from '@/components/ui/Button';
import { useToast } from '@/lib/hooks/useToast';

interface ExportOptionsProps {
  data: {
    original?: {
      title: string;
      description: string;
    };
    optimized: {
      title: string;
      description: string;
      tags: string[];
      seoScore: number;
      improvements?: string[];
      bulletPoints?: string[];
      backendSearchTerms?: string[];
    };
  };
}

export default function ExportOptions({ data }: ExportOptionsProps) {
  const [isOpen, setIsOpen] = useState(false);
  const { success, error } = useToast();

  const generatePDFReport = () => {
    // This would integrate with jsPDF
    success('PDF Report', 'Report generation started. Download will begin shortly.');
    // TODO: Implement PDF generation
  };

  const copyAllText = () => {
    const text = `
LISTING OPTIMIZATION REPORT
===========================

OPTIMIZED TITLE:
${data.optimized.title}

OPTIMIZED DESCRIPTION:
${data.optimized.description}

TAGS:
${data.optimized.tags.join(', ')}

${data.optimized.bulletPoints ? `
BULLET POINTS:
${data.optimized.bulletPoints.map(bullet => `• ${bullet}`).join('\n')}
` : ''}

${data.optimized.backendSearchTerms ? `
BACKEND SEARCH TERMS:
${data.optimized.backendSearchTerms.join(', ')}
` : ''}

SEO SCORE: ${data.optimized.seoScore}/100

${data.optimized.improvements ? `
KEY IMPROVEMENTS:
${data.optimized.improvements.map(imp => `✓ ${imp}`).join('\n')}
` : ''}

Generated by OptiCommerce AI
    `.trim();

    navigator.clipboard.writeText(text);
    success('Copied!', 'All optimization data copied to clipboard');
  };

  const exportToCSV = () => {
    const csvData = [
      ['Field', 'Original', 'Optimized'],
      ['Title', data.original?.title || '', data.optimized.title],
      ['Description', data.original?.description || '', data.optimized.description],
      ['Tags', '', data.optimized.tags.join('; ')],
      ['SEO Score', '', data.optimized.seoScore.toString()],
    ];

    if (data.optimized.bulletPoints) {
      data.optimized.bulletPoints.forEach((bullet, index) => {
        csvData.push([`Bullet Point ${index + 1}`, '', bullet]);
      });
    }

    const csvContent = csvData.map(row => 
      row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(',')
    ).join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'listing-optimization.csv';
    a.click();
    URL.revokeObjectURL(url);

    success('CSV Export', 'CSV file downloaded successfully');
  };

  const emailReport = () => {
    const subject = 'Listing Optimization Report';
    const body = `Hi,

I've optimized a product listing using OptiCommerce AI. Here are the results:

OPTIMIZED TITLE:
${data.optimized.title}

SEO SCORE: ${data.optimized.seoScore}/100

You can view the full report in the attached file.

Best regards`;

    const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoLink);
    
    success('Email Ready', 'Email client opened with report data');
  };

  const saveAsTemplate = () => {
    // This would save to localStorage or backend
    const template = {
      name: `Template - ${new Date().toLocaleDateString()}`,
      data: data.optimized,
      createdAt: new Date().toISOString()
    };
    
    const templates = JSON.parse(localStorage.getItem('optimization-templates') || '[]');
    templates.push(template);
    localStorage.setItem('optimization-templates', JSON.stringify(templates));
    
    success('Template Saved', 'Optimization saved as template for future use');
  };

  const exportOptions = [
    {
      icon: FileText,
      label: 'PDF Report',
      description: 'Professional report with all details',
      action: generatePDFReport
    },
    {
      icon: Copy,
      label: 'Copy All Text',
      description: 'Copy everything to clipboard',
      action: copyAllText
    },
    {
      icon: Download,
      label: 'Export to CSV',
      description: 'Spreadsheet format for analysis',
      action: exportToCSV
    },
    {
      icon: Mail,
      label: 'Email Report',
      description: 'Share via email',
      action: emailReport
    },
    {
      icon: Save,
      label: 'Save as Template',
      description: 'Reuse for similar products',
      action: saveAsTemplate
    }
  ];

  return (
    <div className="relative">
      <Button
        onClick={() => setIsOpen(!isOpen)}
        variant="outline"
        className="w-full flex items-center justify-between"
      >
        <span className="flex items-center gap-2">
          <Download size={16} />
          Export Options
        </span>
        <ChevronDown 
          size={16} 
          className={`transition-transform ${isOpen ? 'rotate-180' : ''}`} 
        />
      </Button>

      {isOpen && (
        <div className="absolute top-full left-0 right-0 mt-2 bg-white border border-gray-200 rounded-lg shadow-lg z-10">
          <div className="p-2 space-y-1">
            {exportOptions.map((option, index) => (
              <button
                key={index}
                onClick={() => {
                  option.action();
                  setIsOpen(false);
                }}
                className="w-full flex items-start gap-3 p-3 text-left hover:bg-gray-50 rounded-lg transition-colors"
              >
                <option.icon size={18} className="text-gray-600 mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-gray-900 text-sm">{option.label}</p>
                  <p className="text-xs text-gray-600 mt-0.5">{option.description}</p>
                </div>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}